name: DBIx-SearchBuilder
version: 1.38
license: perl
distribution_type: module
build_requires:
  Test::More: 0.52
  DBD::SQLite: 0
requires:
  DBI: 0
  Want: 0
  Encode: 0
  Class::ReturnValue: 0.4
  Cache::Simple::TimedExpiry: 0.21
  Clone: 0
no_index:
  directory:
    - t
    - inc
generated_by: Module::Install version 0.46
