---
abstract: 'Encapsulate SQL queries and rows in simple perl objects'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  DBD::SQLite: 0
  ExtUtils::MakeMaker: 6.36
  File::Temp: 0
  Test::More: 0.52
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-SearchBuilder
no_index:
  directory:
    - ex
    - inc
    - t
requires:
  Cache::Simple::TimedExpiry: '0.21'
  Class::Accessor: 0
  Class::ReturnValue: 0.4
  Clone: 0
  DBI: 0
  DBIx::DBSchema: 0
  Encode: '1.99'
  Scalar::Util: 0
  Want: 0
resources:
  license: http://dev.perl.org/licenses/
version: '1.66'
