--- 
abstract: Encapsulate SQL queries and rows in simple perl objects
author: 
  - Jesse Vincent <jesse@bestpractical.com>
build_requires: 
  DBD::SQLite: 0
  File::Temp: 0
  Test::More: 0.52
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-SearchBuilder
no_index: 
  directory: 
    - t
    - ex
    - inc
    - t
requires: 
  Cache::Simple::TimedExpiry: 0.21
  Class::ReturnValue: 0.4
  Clone: 0
  DBI: 0
  Encode: 0
  Want: 0
version: 1.51
