name: DBIx-SearchBuilder
version: 1.10_03
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  DBI: 0
  Want: 0
  Class::ReturnValue: 0.4
  Cache::Simple::TimedExpiry: 0.01
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
