name: DBIx-SearchBuilder
version: 0.97
license: unknown
distribution_type: module
build_requires:
  Test::More: 0
requires:
  DBI: 0
  Class::ReturnValue: 0.4
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
