---
abstract: 'Encapsulate SQL queries and rows in simple perl objects'
author:
  - 'Jesse Vincent <jesse@bestpractical.com>'
build_requires:
  DBD::SQLite: 0
  ExtUtils::MakeMaker: 6.42
  File::Temp: 0
  Test::More: 0.52
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.90'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-SearchBuilder
no_index:
  directory:
    - ex
    - inc
    - t
requires:
  Cache::Simple::TimedExpiry: 0.21
  Class::ReturnValue: 0.4
  Clone: 0
  DBI: 0
  Encode: 1.99
  Want: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.55_01
